name: Dependabot SHA Comment
on: 
  pull_request:

jobs:
  sha-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: timmeinerzhagen/dependabot-sha-comment-action@3224f9c2be2b39f23e2d6381d90c141c38d9593b # v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}